/**
 * Pikmin Bloom 飾品規則與 OpenStreetMap 標籤對應表
 * 
 * 核心原則：
 * 1. 不需要子選項 (扁平大類)
 * 2. 排除無法在地圖獲取花苗的飾品 (已排除: 路邊 Roadside、雨天/下雪 Weather、活動限定 Event、成就飾品)
 * 3. 純向量圖標與專屬主題色 (免額外下載 PNG 圖片，響應極快)
 */

export const DECOR_GROUPS = {
  FOOD: '餐飲美食',
  SHOPPING: '生活購物',
  SERVICES: '日常服務',
  TRANSIT: '交通運輸',
  OUTDOOR: '休閒戶外',
  CULTURE: '文化景點',
};

export const DECOR_RULES = [
  // --- 餐飲美食 (Food & Dining) ---
  {
    id: 'restaurant',
    name: '餐廳',
    nameEn: 'Restaurant',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍴',
    color: '#EF4444',
    tags: ['amenity=restaurant'],
  },
  {
    id: 'cafe',
    name: '咖啡廳',
    nameEn: 'Cafe',
    group: DECOR_GROUPS.FOOD,
    symbol: '☕',
    color: '#8B5CF6',
    tags: ['amenity=cafe'],
  },
  {
    id: 'sweetshop',
    name: '甜點店',
    nameEn: 'Sweetshop',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍰',
    color: '#EC4899',
    tags: ['shop=pastry', 'shop=confectionery', 'shop=chocolate'],
  },
  {
    id: 'bakery',
    name: '麵包店',
    nameEn: 'Bakery',
    group: DECOR_GROUPS.FOOD,
    symbol: '🥐',
    color: '#F59E0B',
    tags: ['shop=bakery'],
  },
  {
    id: 'burger',
    name: '漢堡店',
    nameEn: 'Burger Shop',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍔',
    color: '#EA580C',
    tags: ['amenity=fast_food', 'cuisine=burger'],
  },
  {
    id: 'italian',
    name: '義式餐廳',
    nameEn: 'Italian Restaurant',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍕',
    color: '#10B981',
    tags: ['cuisine=pizza', 'cuisine=italian', 'cuisine=pasta', 'cuisine=mediterranean'],
  },
  {
    id: 'ramen',
    name: '拉麵店',
    nameEn: 'Ramen Shop',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍜',
    color: '#F97316',
    tags: ['cuisine=ramen', 'cuisine=noodle', 'cuisine=udon', 'cuisine=soba', 'cuisine=chinese'],
  },
  {
    id: 'sushi',
    name: '壽司店',
    nameEn: 'Sushi Restaurant',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍣',
    color: '#06B6D4',
    tags: ['cuisine=sushi'],
  },
  {
    id: 'curry',
    name: '咖哩餐廳',
    nameEn: 'Curry Restaurant',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍛',
    color: '#D97706',
    tags: ['cuisine=curry', 'cuisine=indian', 'cuisine=sri_lankan'],
  },
  {
    id: 'korean',
    name: '韓式餐廳',
    nameEn: 'Korean Restaurant',
    group: DECOR_GROUPS.FOOD,
    symbol: '🍲',
    color: '#DC2626',
    tags: ['cuisine=korean'],
  },
  {
    id: 'taco',
    name: '墨西哥餐廳',
    nameEn: 'Mexican / Taco',
    group: DECOR_GROUPS.FOOD,
    symbol: '🌮',
    color: '#EAB308',
    tags: ['cuisine=mexican'],
  },

  // --- 生活購物 (Shopping) ---
  {
    id: 'convenience',
    name: '便利商店',
    nameEn: 'Convenience Store',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '🏪',
    color: '#10B981',
    tags: ['shop=convenience'],
  },
  {
    id: 'supermarket',
    name: '超市',
    nameEn: 'Supermarket',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '🛒',
    color: '#3B82F6',
    tags: ['shop=supermarket', 'shop=greengrocer'],
  },
  {
    id: 'cosmetics',
    name: '化妝品商店',
    nameEn: 'Cosmetics',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '💄',
    color: '#F43F5E',
    tags: ['shop=cosmetics', 'shop=beauty', 'shop=department_store'],
  },
  {
    id: 'clothing',
    name: '服飾店',
    nameEn: 'Clothing Store',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '👔',
    color: '#6366F1',
    tags: ['shop=clothes', 'shop=shoes', 'shop=fashion'],
  },
  {
    id: 'electronics',
    name: '電器行',
    nameEn: 'Electronics',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '🔌',
    color: '#38BDF8',
    tags: ['shop=electronics', 'shop=appliance', 'shop=computer', 'shop=mobile_phone'],
  },
  {
    id: 'hardware',
    name: '五金行',
    nameEn: 'Hardware Store',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '🔧',
    color: '#64748B',
    tags: ['shop=hardware', 'shop=doityourself', 'shop=tools'],
  },
  {
    id: 'library',
    name: '圖書館／書店',
    nameEn: 'Library & Bookstore',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '📚',
    color: '#0D9488',
    tags: ['amenity=library', 'shop=books'],
  },
  {
    id: 'stationery',
    name: '文具店',
    nameEn: 'Stationery Store',
    group: DECOR_GROUPS.SHOPPING,
    symbol: '✏️',
    color: '#EAB308',
    tags: ['shop=stationery', 'shop=craft'],
  },

  // --- 日常服務 (Services) ---
  {
    id: 'pharmacy',
    name: '藥局',
    nameEn: 'Pharmacy',
    group: DECOR_GROUPS.SERVICES,
    symbol: '💊',
    color: '#14B8A6',
    tags: ['amenity=pharmacy', 'shop=chemist', 'healthcare=pharmacy'],
  },
  {
    id: 'hair_salon',
    name: '美髮院',
    nameEn: 'Hair Salon',
    group: DECOR_GROUPS.SERVICES,
    symbol: '💈',
    color: '#A855F7',
    tags: ['shop=hairdresser'],
  },
  {
    id: 'laundry',
    name: '洗衣店',
    nameEn: 'Laundromat',
    group: DECOR_GROUPS.SERVICES,
    symbol: '🧺',
    color: '#0284C7',
    tags: ['shop=laundry', 'shop=dry_cleaning'],
  },
  {
    id: 'post_office',
    name: '郵局',
    nameEn: 'Post Office',
    group: DECOR_GROUPS.SERVICES,
    symbol: '📮',
    color: '#16A34A',
    tags: ['amenity=post_office', 'amenity=post_box'],
  },
  {
    id: 'hotel',
    name: '飯店',
    nameEn: 'Hotel',
    group: DECOR_GROUPS.SERVICES,
    symbol: '🏨',
    color: '#8B5CF6',
    tags: ['tourism=hotel', 'tourism=motel', 'tourism=hostel', 'tourism=guest_house'],
  },
  {
    id: 'university',
    name: '大學＆學院',
    nameEn: 'University',
    group: DECOR_GROUPS.SERVICES,
    symbol: '🎓',
    color: '#4338CA',
    tags: ['amenity=university', 'amenity=college', 'building=university'],
  },

  // --- 交通運輸 (Transportation) ---
  {
    id: 'station',
    name: '車站',
    nameEn: 'Train Station',
    group: DECOR_GROUPS.TRANSIT,
    symbol: '🚆',
    color: '#0284C7',
    tags: ['railway=station', 'building=train_station', 'railway=subway_entrance', 'public_transport=station'],
  },
  {
    id: 'bus_stop',
    name: '公車站',
    nameEn: 'Bus Stop',
    group: DECOR_GROUPS.TRANSIT,
    symbol: '🚏',
    color: '#2563EB',
    tags: ['highway=bus_stop', 'amenity=bus_station', 'public_transport=platform'],
  },
  {
    id: 'airport',
    name: '機場',
    nameEn: 'Airport',
    group: DECOR_GROUPS.TRANSIT,
    symbol: '✈️',
    color: '#0ea5e9',
    tags: ['aeroway=aerodrome', 'aeroway=terminal', 'aeroway=gate'],
  },
  {
    id: 'bridge',
    name: '橋樑',
    nameEn: 'Bridge',
    group: DECOR_GROUPS.TRANSIT,
    symbol: '🌉',
    color: '#64748b',
    tags: ['bridge=yes', 'man_made=bridge'],
  },

  // --- 休閒戶外 (Outdoor & Nature) ---
  {
    id: 'park',
    name: '公園',
    nameEn: 'Park',
    group: DECOR_GROUPS.OUTDOOR,
    symbol: '🌳',
    color: '#16A34A',
    tags: ['leisure=park', 'leisure=garden', 'leisure=playground', 'landuse=village_green'],
  },
  {
    id: 'forest',
    name: '森林',
    nameEn: 'Forest',
    group: DECOR_GROUPS.OUTDOOR,
    symbol: '🌲',
    color: '#15803D',
    tags: ['natural=wood', 'landuse=forest'],
  },
  {
    id: 'waterside',
    name: '水邊',
    nameEn: 'Waterside',
    group: DECOR_GROUPS.OUTDOOR,
    symbol: '🌊',
    color: '#06B6D4',
    tags: ['natural=water', 'natural=wetland', 'waterway=river', 'waterway=stream', 'waterway=canal'],
  },
  {
    id: 'beach',
    name: '海邊',
    nameEn: 'Beach',
    group: DECOR_GROUPS.OUTDOOR,
    symbol: '🏖️',
    color: '#F59E0B',
    tags: ['natural=beach'],
  },
  {
    id: 'mountain',
    name: '山丘',
    nameEn: 'Mountain',
    group: DECOR_GROUPS.OUTDOOR,
    symbol: '⛰️',
    color: '#78716C',
    tags: ['natural=peak', 'natural=cliff', 'natural=bare_rock'],
  },

  // --- 文化景點 (Culture & Recreation) ---
  {
    id: 'zoo',
    name: '動物園',
    nameEn: 'Zoo',
    group: DECOR_GROUPS.CULTURE,
    symbol: '🦁',
    color: '#D97706',
    tags: ['tourism=zoo', 'tourism=aquarium'],
  },
  {
    id: 'theme_park',
    name: '主題樂園',
    nameEn: 'Theme Park',
    group: DECOR_GROUPS.CULTURE,
    symbol: '🎢',
    color: '#8B5CF6',
    tags: ['tourism=theme_park', 'leisure=water_park'],
  },
  {
    id: 'art_gallery',
    name: '美術館／博物館',
    nameEn: 'Museum & Gallery',
    group: DECOR_GROUPS.CULTURE,
    symbol: '🎨',
    color: '#EC4899',
    tags: ['tourism=museum', 'tourism=gallery', 'shop=art', 'amenity=arts_centre'],
  },
  {
    id: 'stadium',
    name: '體育館',
    nameEn: 'Stadium',
    group: DECOR_GROUPS.CULTURE,
    symbol: '🏟️',
    color: '#2563EB',
    tags: ['leisure=stadium', 'leisure=sports_centre', 'building=stadium'],
  },
  {
    id: 'movie_theater',
    name: '電影院',
    nameEn: 'Cinema',
    group: DECOR_GROUPS.CULTURE,
    symbol: '🎬',
    color: '#9333EA',
    tags: ['amenity=cinema'],
  },
  {
    id: 'shrine',
    name: '神社／寺廟',
    nameEn: 'Shrine / Temple',
    group: DECOR_GROUPS.CULTURE,
    symbol: '⛩️',
    color: '#DC2626',
    tags: ['amenity=place_of_worship'],
  },
];

export const DECOR_RULES_MAP = new Map(DECOR_RULES.map(rule => [rule.id, rule]));

export function getDecorRule(id) {
  return DECOR_RULES_MAP.get(id);
}

export function getAllDecorIds() {
  return DECOR_RULES.map(r => r.id);
}
